name: Nature Client Auto-Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Unzip Files
      run: |
        powershell Expand-Archive -Path "'Nature Client.zip'" -DestinationPath "."
        dir

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build DLL
      run: |
        $sln = Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1
        if ($sln) {
          msbuild $sln.FullName /p:Configuration=Release /p:Platform=x64
        } else {
          Write-Error "Bhai, .sln file nahi mili zip ke andar!"
        }

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Nature-DLL-Package
        path: "**/*.dll"
        
        
